In [20]:
import numpy as np

In [14]:
a = 5.2

In [15]:
b = 0
c = 1

In [16]:
whos

Variable   Type     Data/Info
-----------------------------
a          float    5.2
b          int      0
c          int      1


In [17]:
del a

In [18]:
whos

Variable   Type    Data/Info
----------------------------
b          int     0
c          int     1


In [7]:
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


In [8]:
whos

Interactive namespace is empty.


In [24]:
X = np.zeros((2, 3))
print(X)
Y = np.ones((3, 4))
print(Y)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [25]:
np.ones_like(X)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
vect_x = np.array([5, 6.0, 8, 2])
print(vect_x)

[5. 6. 8. 2.]


In [36]:
print(X.shape)
print(vect_x.shape)

(2, 3)
(4,)


In [42]:
vect_x = np.reshape(vect_x, (2, 2))

In [43]:
print(vect_x.shape)

(2, 2)


In [46]:
X = np.array([[1, 2, 3], [4, 5, 6]])
print(X)
print(np.reshape(X, (2, 3)))
print(np.reshape(X, (3, 2)))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [49]:
w = np.random.rand(3, 1)
print(w.shape)

(3, 1)


In [51]:
print(np.dot(X, w))

[[2.93571812]
 [8.47737425]]


In [68]:
print(X)

[[1 2 3]
 [4 5 6]]


In [67]:
print(X[0, 1])

2


In [61]:
for x in X:
    print(x)

[1 2 3]
[4 5 6]


In [63]:
for i in range(1, 11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [69]:
v = np.zeros((3, 1))
u = np.zeros((1, 3))

In [70]:
whos

Variable   Type       Data/Info
-------------------------------
X          ndarray    2x3: 6 elems, type `int64`, 48 bytes
Y          ndarray    3x4: 12 elems, type `float64`, 96 bytes
b          int        0
c          int        1
i          int        10
np         module     <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
u          ndarray    1x3: 3 elems, type `float64`, 24 bytes
v          ndarray    3x1: 3 elems, type `float64`, 24 bytes
vect_x     ndarray    2x2: 4 elems, type `float64`, 32 bytes
w          ndarray    3x1: 3 elems, type `float64`, 24 bytes
x          ndarray    3: 3 elems, type `int64`, 24 bytes


In [71]:
print(v)
print(u)

[[0.]
 [0.]
 [0.]]
[[0. 0. 0.]]
